### ISSUE TITLE
Add tests for DNSPolicy Health Checks

### ISSUE THREAD

**Issue by averevki** [Kuadrant/testsuite#256]
**Summary**

"_DNS Health Checks are a crucial tool for ensuring the availability and reliability of your multi-cluster applications. Kuadrant offers a powerful feature known as [DNSPolicy](https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/), which allows you to configure and verify health checks for DNS endpoints._"

**Documentation**

- DNSPolicy Health Checks: https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-health-checks/

**Test cases**
- [x] Health Checks https://github.com/Kuadrant/testsuite/issues/254
- [ ] DNSRecord endpoint removal https://github.com/Kuadrant/testsuite/issues/264
- [ ] Metrics https://github.com/Kuadrant/testsuite/issues/255
- [ ] HTTP Headers Secret https://github.com/Kuadrant/testsuite/issues/252

**Comment by azgabur** [comment]
Health checks are being reworked now https://github.com/Kuadrant/dns-operator/issues/151

**Comment by averevki** [comment]
Closed in favor of #572
