### ISSUE TITLE
Add tests for kuadrantctl CLI tool

### ISSUE THREAD

**Issue by azgabur** [Kuadrant/testsuite#365]
**Summary**

kuadrantctl is a CLI tool for installing/uninstalling Kuadrant and generating Kuadrant resources HTTPRoute, AuthPolicy, and RateLimitPolicy from OpenAPI specification.

**Documentation**

https://github.com/Kuadrant/kuadrantctl

**Test cases**

- [ ] [Generating Gateway API HTTPRoute Objects](https://github.com/Kuadrant/kuadrantctl/blob/main/doc/generate-gateway-api-httproute.md)
- [ ] [Generating Kuadrant AuthPolicy Objects](https://github.com/Kuadrant/kuadrantctl/blob/main/doc/generate-kuadrant-auth-policy.md)
- [ ] [Generating Kuadrant RateLimitPolicy Objects](https://github.com/Kuadrant/kuadrantctl/blob/main/doc/generate-kuadrant-rate-limit-policy.md)
